# These are supported funding model platforms

github: "Fred1e", "mr-X-force", "frecyber1" # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: "frediezra" # Replace with a single Patreon username
open_collective: "frediezra" # Replace with a single Open Collective username
ko_fi: "frediezra" # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: "LUCKY-MD-XFORCE" # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: "frediezra" # Replace with a single Liberapay username
issuehunt: "frediezra" # Replace with a single IssueHunt username
lfx_crowdfunding: "LUCKY-MD-XFORCE" # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: "frediezra" # Replace with a single Polar username
buy_me_a_coffee: "frediezra265" # Replace with a single Buy Me a Coffee username
thanks_dev: "Fred1e" # Replace with a single thanks.dev username
custom: "https://sociabuzz.com/frediezra255", "https://fredietech-website.vercel.app", "https://whatsapp.com/channel/0029VaihcQv84Om8LP59fO3f" # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
